--- 
javascripts: 
- base: 
  - jquery-1.3.2.min
  - jquery-ui-1.7.2.custom.min
  - jquery_rails_ujs_helper
  - application
  
stylesheets: 
- base:
  - application
  - smoothness/jquery-ui-1.7.2.custom
- base_ie:
  - ie
- base_print:
  - print
