--- 
javascripts: 
- base:
  - jquery-1.3.2.min
  - jquery-ui-1.7.2.custom.min
  - jquery_rails_ujs_helper
  - jquery.tablesorter.min
  - application

- admin_base:
  - jquery-1.3.2.min
  - jquery-ui-1.7.2.custom.min
  - hoverIntent
  - superfish
  - jquery.lightbox-0.5.min
  - jquery_rails_ujs_helper
  - /markitup/jquery.markitup.pack.js
  - /markitup/sets/html/set.js
  - admin
  
stylesheets: 
- base:
  - application
  - plugins/jquery.lightbox-0.5.css
  - tablesorter/tablesorter.css
- base_ie:
  - ie
- base_print:
  - print
- admin_session:
  - session
- admin_base:
  - admin
  - plugins/jquery-ui-1.7.2.custom.css
  - plugins/jquery.lightbox-0.5.css
  - plugins/superfish.css
  - /markitup/skins/simple/style.css
  - /markitup/sets/html/style.css
